### ISSUE TITLE
"item" patch + \bgroup -> "Use of \MT@prot@group doesn't match its definition."

### ISSUE THREAD

**Issue by urrameu** [schlcht/microtype#10]
## Description

The patches to "item" apparently cause problems if the item text starts with a `\bgroup`, resulting in the error "Use of \MT@prot@group doesn't match its definition." This affects pdflatex, xelatex, and lualatex.

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{microtype}
\begin{document}
\begin{itemize}
\item \bgroup Hi there!\egroup
\end{itemize}
\end{document}
```

As a workaround, if there is something before `\bgroup` (for example, `\null`), things work ok. Another workaround is to use `\begingroup` instead of `\bgroup`.

**Comment by schlcht** [comment]
An even simpler workaround would be to just use parentheses ... but of course I agree that this is a bug that needs to be fixed

**Comment by urrameu** [comment]
> Could you try with
> 
> ```
> \def\MT@prot@group{\bgroup\afterassignment\MT@prot@get@firstchar\let\MT@temp= }
> ```

WorksForMe<sup>(TM)</sup> :)

However, I will create another related issue that is *not* solved by this :-/ .
