### ISSUE TITLE
Unable to patch footnote in doc using `setspace`

### ISSUE THREAD

**Issue by callegar** [schlcht/microtype#11]
## Description

Getting the "unable to patch footnote" warning with the latest (today's) microtype on a lualatex document.
Doc uses  `setspace`. 

## Minimal example demonstrating the issue
```LaTeX
\documentclass{article}
\usepackage{microtype}
\usepackage{hyperref}
\usepackage{setspace}

\begin{document}
test
\end{document}
```

**Comment by schlcht** [comment]
You should load `setspace` before `hyperref`. The `setspace` package overwrites `hyperref`'s definition of `\@footnotetext`, which will not only make microtype fail to apply its own patch, but also break footnote hyperlinks. I consider this a bug in `setspace`, so I'm closing this here.

**Comment by yustiks** [comment]
> You should load `setspace` before `hyperref`. The `setspace` package overwrites `hyperref`'s definition of `\@footnotetext`, which will not only make microtype fail to apply its own patch, but also break footnote hyperlinks. I consider this a bug in `setspace`, so I'm closing this here.

worked for me perfectly!
