### ISSUE TITLE
fontsize changes in \textls affect following \lslig commands

### ISSUE THREAD

**Issue by u-fischer** [schlcht/microtype#12]
## Description

After changing the fontsize locally in a \textls following \lslig command continue to use this size. 
This happens e.g. if `\footnote` or `\textsuperscript` is used:

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{microtype}

\begin{document}

\textls{a\lslig{ff}e\textsuperscript{1} a\lslig{ff}e}

\textls{a\lslig{ff}e {\footnotesize small} a\lslig{ff}e}

\textls{a\lslig{ff}e {\LARGE Large} a\lslig{ff}e}
\end{document}

```

![image](https://user-images.githubusercontent.com/4047173/155841590-86d61760-24f5-4e3b-a212-8a9036fc2b89.png)

**Comment by schlcht** [comment]
ah yes, `\font@name` isn't always guaranteed to reflect the current font (not only size). 

Could you try with the `dev` version, or just:
```
\DeclareRobustCommand\lslig[1]{%
  {\MT@ifdefined@c@TF\MT@curr@ls{%
     \escapechar\m@ne
     \xdef\font@name{\csname\curr@fontshape/\f@size\endcsname}%
     \MT@get@ls@basefont
     \MT@outer@kern=\dimexpr\MT@curr@ls sp * \fontdimen6\font@name/2000\relax
     \kern\MT@outer@kern
     \font@name #1%
     \kern\MT@outer@kern
  }{#1}}%
}
```
