### ISSUE TITLE
empty \item[] with beamer causes "Paragraph ended before \@car was complete" error

### ISSUE THREAD

**Issue by urrameu** [schlcht/microtype#13]
## Description

The "item" patches may cause problems in beamer with an empty `\item[]` (I use this to add vertical spacing, which is not "the true LaTeX way").

This affects pdflatex, xelatex, and lualatex.

## Minimal example demonstrating the issue
```
\documentclass{beamer}
\usepackage{microtype}
\begin{document}
\begin{frame}
\begin{itemize}
\item First
\item[]
\item Third
\end{itemize}
\end{frame}
\end{document}
```

A workaround is to add `\strut` to the empty item.

The fix suggested in https://github.com/schlcht/microtype/issues/10#issuecomment-1052262618 does not fix this problem.

**Comment by schlcht** [comment]
works for me with the current version 3.0c. Could you add the log file?

**Comment by urrameu** [comment]
Oops, my bad, I did not realize there was a 3.0c version; the problem only appears with 3.0b. Closing.
