### ISSUE TITLE
Incorrect equation numbering with amsmath, cases packages.

### ISSUE THREAD

**Issue by bdtc** [schlcht/microtype#14]
## Description

pdflatex
microtype 2022/02/22
cases 2020/03/29
amsmath 2021/10/15

In cases.sty, numcases environment, line 57, is the following:

` \settowidth{\numc@numwid}{\ \advance\c@equation\tw@\numc@eqnnum}%`

If microtype is used, the counter advance is somehow not kept local.

The problem appears to be related to \leftprotrusion and/or \rightprotrusion
when used by microtype to patch \tagform@ or \@eqnnum, depending on whether
amsmath is loaded.  Some kind of fancy token lookahead is used.

From microtype.sty, starting at line 691:
```
    \@ifpackageloaded{amsmath}
      {\MT@patch@patch\tagform@{(}{\leftprotrusion{(}}%
       \MT@patch@patch\tagform@{)}{\rightprotrusion{)}}%
       \MT@patch@patch\eqref{\tagform@}{\@nameuse{MT@patch@saved@\string\tagform@}}}
      {\MT@patch@patch\@eqnnum{(}{\leftprotrusion{(}}%
       \MT@patch@patch\@eqnnum{)}{\rightprotrusion{)}}}%

```
If those patches are undone, cases works fine.

## Minimal example demonstrating the issue
```
\documentclass{article}

\usepackage{microtype}% causes incorrect equation numbering

\usepackage{cases}

\begin{document}

\begin{numcases}{|x|=}
x, & for $x \geq 0$\\
-x, & for $x < 0$
\end{numcases}

\end{document}
```

**Comment by schlcht** [comment]
`cases` makes a trial run, and so does `microtype`, and both interfere in a bad way with regards to the value of `\c@equation`. Fortunately, this can be solved easily as `microtype` actually no longer needs to save and reset counter values. The following (or the current `dev` branch) should fix the issue:

```
\def\MT@get@prot#1#2{%
  \begingroup
    \setbox\MT@tempbox\vbox{%
      \everypar{}%
      \parfillskip=\z@skip
      \hbadness\@M
      \clubpenalty\z@
      \widowpenalty\z@
      \interlinepenalty\z@
      \@newlistfalse
      \MT@prot@hook
      \MT@noindent #1\MT@csq@eqgroup}%
    \vbadness=\@M
    \splittopskip=\z@
    \vfuzz=\maxdimen
    \setbox\MT@tempbox\vbox{%
      \ifvbox\MT@tempbox
        \global\setbox\MT@tempbox=\vsplit\MT@tempbox to \normalbaselineskip
        \unvbox\MT@tempbox
        \global\setbox\MT@tempbox=\lastbox
      \fi
    }%
  \endgroup
  \leavevmode
  \ifhbox\MT@tempbox
    \@tempdima=\@nameuse{#2marginkern}\MT@tempbox\relax
    \expandafter\ifdim\@tempdima=\z@ \else
      \MT@vinfo{|<< adding #2 margin kern for `#1':\MessageBreak
        \the\@tempdima \on@line}%
      \kern\@tempdima
    \fi
  \fi
}
```
