### ISSUE TITLE
Conflict with stage package

### ISSUE THREAD

**Issue by dbenjaminmiller** [schlcht/microtype#15]
## Description
Beginning (it seems) with the latest release, using microtype when the `stage` documentclass is used causes an error on `charsd`

```
! Missing { inserted.
<to be read again> 
                   (
l.5 \dialogue{Second}{\charsd{Enters} Why, hello!}
                                                  
?
```

## Minimal example demonstrating the issue

```
\documentclass{stage}
\usepackage{microtype}
\begin{document}
\dialogue{First}{Hello}
\dialogue{Second}{\charsd{Enters} Why, hello!}
\end{document}
```

(conflicting with)

```
\newcommand{\charsd}[1]{%
	{\def\everypar{\parskip=0pt\stageoldep}%
	\stage{#1}\par\leavevmode}}
```

**Comment by schlcht** [comment]
Redefining the `\everypar` primitive this way is a _very_ bad idea, and should also fail without microtype in many other cases. The reason why the issue crops up only with the latest release of microtype is that latex's handling of everypar has changed, to which microtype has been adapted. But this is definitely a bug in the stage class, so please report [there](https://github.com/rrthomas/stage).
