### ISSUE TITLE
Unable to patch footnote in memoir documents with hyperref loaded

### ISSUE THREAD

**Issue by ccwang002** [schlcht/microtype#2]
## Description
microtype v3.0 is unable to patch `footnote` in memoir documents that load the hyperref package. I was able to reproduce the warning on pdfTeX, LuaTeX, and XeTeX.

Thanks for making this package!

## Minimal example demonstrating the issue
```latex
\documentclass{memoir}
\usepackage{microtype}
\usepackage{hyperref}

\begin{document}
Hi
\end{document}
```

```
Package microtype Warning: Unable to apply patch `footnote' on input line 12.
```

Patching will be successful without hyperref package. It also works if I replace memoir with the standard LaTeX document classes like article and book.

**Comment by MisterFiLou** [comment]
I have the same warning in report documents. 
I also use the hyperref package.

**Comment by schlcht** [comment]
> I have the same warning in report documents. 

If I replace `memoir` with `report` in @ccwang002's example, I don't get any warning. Could you provide a minimal example?

**Comment by schlcht** [comment]
> microtype v3.0 is unable to patch `footnote` in memoir documents that load the hyperref package. 

Thanks, could you  try with the `dev` version, or by copying the following into your preamble: 

```
\microtypesetup{nopatch=footnote}
\makeatletter
\catcode`\#=12
  \MT@define@patch{footnote1}{%
    \@ifpackageloaded{hyperref}{%
      \MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
      \MT@patch@patch\@footnotetext{\@empty\ignorespaces}{\@empty\ignorespaces\leftprotrusion}%
    }{%
      \@ifpackageloaded{scrbase}
        {\MT@patch@patch\scr@saved@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}}
        {\MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
         \@ifclassloaded{memoir}
           {\MT@patch@patch\@footnotetext{\foottextfont #1}{\foottextfont\leftprotrusion #1}}
           {}}%
    }%
  }{}%
\catcode`\#=6
\makeatother
```

**Comment by ccwang002** [comment]
Thank you for your incredibly fast fix! I can confirm that the warning goes away with the fix.

```
Package microtype Info: Applying patch `footnote1' on input line 24.
```

**Comment by MisterFiLou** [comment]
I did some further testing. 
Seems that the warning is not related to the hyperref package, but occurs in combination with the svg package.

```
\documentclass{report}

\usepackage{svg}
\usepackage{microtype} %micro typography

\begin{document}

\end{document}
```

**Comment by schlcht** [comment]
Ah yes, the test (in the above code) should be for package `scrkbase`, not `scrbase`.

**Comment by MisterFiLou** [comment]
@schlcht
Indeed, if I replace `scrbase `with `scrkbase`, works fine, no warning anymore.

I guess an update for the microtype package is coming?

**Comment by schlcht** [comment]
@MisterFiLou update is on its way to CTAN ...

**Comment by MisterFiLou** [comment]
Thanks for the fast response.
Thanks for the package.

**Comment by bhomaidan1990** [comment]
Hi,

I'm using **Beamer** and the problem is still, I'm using **Overleaf**:  `PdfLaTex`, `Tex v: 2022`, can you please tell me how I can resolve this problem? thanks in advance.

```sh
Package microtype Warning: Unable to apply patch `footnote1' on input line 37.
```

Here is my **MWE**:
```tex
\documentclass[aspectratio=169, professionalfonts, t,xcolor=table]{beamer}

\usepackage[utf8]{inputenc}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage{hyperref}

\makeatletter
\MT@redefine@patch{eqnum}{%
  \MT@patch@patch\tagform@{(}{\leftprotrusion{(}}%
  \MT@patch@patch\tagform@{)}{\rightprotrusion{)}}%
  \MT@ifdefined@n@TF{eqref }
    {\MT@exp@cs\MT@patch@patch{eqref }}{\MT@patch@patch\eqref}
       {\tagform@}{\@nameuse{MT@patch@saved@\string\tagform@}}%
}{}
\makeatother

\microtypesetup{nopatch=footnote}
\makeatletter
\catcode`\#=12
  \MT@define@patch{footnote1}{%
    \@ifpackageloaded{hyperref}{%
      \MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
      \MT@patch@patch\@footnotetext{\@empty\ignorespaces}{\@empty\ignorespaces\leftprotrusion}%
    }{%
      \@ifpackageloaded{scrkbase}
        {\MT@patch@patch\scr@saved@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}}
        {\MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
         \@ifclassloaded{memoir}
           {\MT@patch@patch\@footnotetext{\foottextfont #1}{\foottextfont\leftprotrusion #1}}
           {}}%
    }%
  }{}%
\catcode`\#=6
\makeatother


\begin{document}
Hi.
\end{document}
```

**Comment by schlcht** [comment]
Remove all the code between `\makeatletter` and `\makeatother` (both). This was meant to be a temporary fix until the package itself would be updated. Without this extra code, your example compiles without warning.

**Comment by bhomaidan1990** [comment]
@schlcht removing the patches yields two warnings instead of one, here is the [link to **overleaf** MWE](https://www.overleaf.com/3141827865pzgjwmpyghfb)

**Comment by schlcht** [comment]
This most probably means that Overleaf provides an old version of microtype. The optimal solution would be to install the current version (but I wouldn't be able to tell how to do that in Overleaf). Going back to an old TeXLive version only to prevent these innocuous warnings seems overkill, so if you can't use the latest microtype version, I'd recommend to load it with: `\usepackage[nopatch={eqnum,footnote}]{microtype}`.
