### ISSUE TITLE
Failure to compile a document with microtype v3.0e

### ISSUE THREAD

**Issue by scottkosty** [schlcht/microtype#21]
## Description
I received an error after the new version, when using pdfTeX.

## Minimal example demonstrating the issue

The following document compiled successfully before the update of microtype to v3.0e.

```
\documentclass[english,hebrew]{scrartcl}
\usepackage[HE8,T1]{fontenc}
\usepackage[latin9,cp1255]{inputenc}
\usepackage{microtype}

\makeatletter
\providecommand{\l@chapter}{\relax}
\makeatother
\usepackage{babel}
\begin{document}
\title{}\maketitle

\end{document}
```

Here is my log with the error: 
[bad.log](https://github.com/schlcht/microtype/files/8983651/bad.log)

Unfortunately, I don't know much about LaTeX, Hebrew, or microtype :). This is not a document I wrote. I am just running a bunch of tests after tlmgr update and this one happened to fail. If the document was compiling just by luck before the microtype update, no problem if you want to close this as "wontfix".

Thanks for all of your work on microtype!

**Comment by schlcht** [comment]
Hm, babel-hebrew redefines `\everypar` in a very bad way (`\def\everypar#1{...}`), which should also fail in many other cases, so I'm quite tempted to just say "report elsewhere" (however, that package has been last updated in 2005, so it's unsure whether it's even still maintained). I'll check if microtype can do anything about this to at least die gracefully though.

**Comment by scottkosty** [comment]
Thanks for taking the time to take a deep look at it! I don't understand the technical issue at all, but I really appreciate you opening the latex2e report even though this does not seem to be microtype's responsibility.

**Comment by scottkosty** [comment]
@schlcht I just tried the minimal example on an updated TeX Live 2023 system and it compiles without error. babel-hebrew seems to have not been updated, and the latex2e issue you opened hasn't had any movement. Any idea if the core issue has been fixed?

**Comment by schlcht** [comment]
what a nice surprise... It seems this has been fixed with version 3.1, albeit inadvertently (I'm not even sure how, I suppose `\leftprotrusion` has become a bit more careful). Though I still think babel-hebrew's `\everypar` redefinition is deeply flawed, and the `\noindent`/`\RawNoindent` issue also remains to be sorted out, so other problems may be lurking, I'm happy to be able to close this issue at least for now. So thanks for your comment!

**Comment by scottkosty** [comment]
Great, thank you for your careful attention and explanations! Sounds like we should leave [#880](https://github.com/latex3/latex2e/issues/880) open.

**Comment by schlcht** [comment]
yes, that should remain open as it concerns other situations and packages, too.
