### ISSUE TITLE
Quotation marks from csquotes package do not protrude correctly within itemize and enumerate environments despite 3.0c patch

### ISSUE THREAD

**Issue by ShenZhouHong** [schlcht/microtype#25]
## Description

**I am using microtype version: 3.0f**

When using quote commands (e.g. `\enquote`, `enquote*`, etc.) offered by the `csquotes` package within an `itemize` or `enumerate` environment, protrusion settings for the quotation marks do not work correctly. This is most evident when using custom protrusion settings defined by microtype's `\SetProtrusion` command, especially when attempting to implement hanging punctuation.

Note that this question is closely related to the issue reported on January 4th, 2022 by tex.stackexchange.com user [NightShade](https://tex.stackexchange.com/users/260836/nightshade). 

https://tex.stackexchange.com/questions/629068/

Likewise, [Marcel Krüger](https://tex.stackexchange.com/users/80496/marcel-kr%c3%bcger)'s LuaLaTeX answer works and solves the problem. However, it has been stated that this issue should be fixed in microtype version 3.0c, and it appears the fix is no longer working as of microtype version 3.0f.

## Minimal example demonstrating the issue
Please compile using the LuaLaTeX engine.

```shell
lualatex document.tex
```

### The contents of `document.tex`

```latex
\documentclass[12pt]{article}
\usepackage{libertinus-otf}
\usepackage{microtype}
\usepackage{csquotes}

\SetProtrusion{encoding = *}{
  \textquotedblleft  = {1000,     },
  \textquotedblright = {    , 1000},
  \textquoteleft     = {1000,     },
  \textquoteright    = {    , 1000}
}

\begin{document}
\paragraph*{Demonstration using enumerate environment}

First please observe how regular protrusion works correctly within paragraphs. Here's an example below:\\
\enquote{However, protrusion does not work within enumerate and itemize.}

\begin{enumerate}
    \item Regular list item without quotations.
    \item \enquote{List item in enumerate quoted with csquote double-quotes.}
    \item Second list item without quotations.
    \item \enquote*{List item in enumerate quoted with csquote single-quotes.}
\end{enumerate}

\paragraph*{Demonstration using itemize environment}
\begin{itemize}
    \item Regular list item without quotations.
    \item \enquote{List item in enumerate quoted with csquote double-quotes.}
    \item Second list item without quotations.
    \item \enquote*{List item in enumerate quoted with csquote single-quotes.}
\end{itemize}
\end{document}
```

### The `document.pdf` contents

![image](https://user-images.githubusercontent.com/6318461/203541958-95c7338f-ec7f-402e-a266-e294c8240138.png)

### Expected behaviour
 In here, `document.pdf` generated with [Marcel Krüger](https://tex.stackexchange.com/users/80496/marcel-kr%c3%bcger)'s answer ([link here)](https://tex.stackexchange.com/a/629080)

![image](https://user-images.githubusercontent.com/6318461/203542991-b3ed71e0-4e9e-41be-82d0-e9bcffade5c3.png)

It looks like perhaps there might have been some regression to the 3.0c patch in later versions of microtype.

**Comment by schlcht** [comment]
It's not really a regression, since the issue from TeX.SX involved active characters (via `\MakeOuterQuote`), whereas you are using the `\enquote` command, which was never recognised by `\leftprotrusion`. But I agree it should be supported, and I'll see what I can do...

**Comment by ShenZhouHong** [comment]
Ah, thank you, I am glad that it is not a regression. In the meantime, is there anything that myself, the end-user can do to resolve this issue, or should I use [Marcel Krüger](https://tex.stackexchange.com/users/80496/marcel-kr%c3%bcger)'s lua protrusion boundary script as a workaround until microtype supports the \enquote command?

**Comment by schlcht** [comment]
If Marcel's solution is working for then this would probably be the best idea for the time being...

**Comment by schlcht** [comment]
Actually I think the following might already be enough to fix this issue:

```
\g@addto@macro\MT@prot@check@cmds{{A\enquote}}
\def\MT@prot@check@A{%
  \def\MT@temp*##1{\@ifstar{\MT@prot@l{\MT@prot@next*}}{\MT@prot@l{\MT@prot@next}}}}
```

Could you try (instead of Marcel's code)?

**Comment by ShenZhouHong** [comment]
Hello there, I can confirm that the above snippet works, for the `\enquote` and `\enquote*` commands. They both allow the quotation mark to protrude correctly in the left margin. However, it does not work for `\textcquote`, which is the other quotation command offered by the `csquotes` package. Marcel's code works for both `\enquote` and `\textcquote`.

**Comment by schlcht** [comment]
could you try with the [dev branch](https://github.com/schlcht/microtype/tree/dev)? I think I got all csquotes commands covered now.
