### ISSUE TITLE
Footnote patching fails with `typearea` package

### ISSUE THREAD

**Issue by dcpurton** [schlcht/microtype#26]
## Description

When just the `typearea` package is loaded (without other parts of the KOMA bundle), `microtype` wrongly thinks it needs to patch the KOMA footnote definition.

`microtype` tests if `scrkbase` is loaded. `typearea` loads this, but it does not contain a definition of `\scr@saved@footnotetext` (which is presumably defined in other places).

This is engine independent.

## Minimal example demonstrating the issue

```
\documentclass{article}
\usepackage[verbose]{microtype}
\usepackage{typearea}
\begin{document}
\null
\end{document}
```

**Comment by schlcht** [comment]
Thanks for the report. This is already fixed in dev (2bdb8a10), with microtype now testing for the macro `\KOMAClassName` instead of the package `scrkbase`.
