### ISSUE TITLE
microtype v3.0a is not compatible with book class

### ISSUE THREAD

**Issue by akiyks** [schlcht/microtype#3]
## Description

microtype v3.0a stopped working with a document of the book class, which has a title page and a footnote, with hyperref.

_Please also indicate the engine(s) with which the issue occurs: pdfTeX

## Minimal example demonstrating the issue (works with v3.0)
```
\documentclass{book}
\usepackage{lmodern}
\usepackage{hyperref}
\usepackage{microtype}

\title{Test of microtype}
\author{A microtype User}

\begin{document}

\frontmatter

\maketitle

\mainmatter

\chapter{Test 1}

Xxxx yyyy zzzz.\footnote{
  Aaaa bbbb cccc.}

\end{document}
```

With v3.0a, pdflatex stops with the error of:
```
[...]
(./main.aux) (/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/gettitlestring/gettitlestring.s
ty)) (/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/mt-cmr.cfg)
Runaway argument?
{\scantokens {\LARGE \@title 
! Paragraph ended before \MT@prot@l was complete.
<to be read again> 
                   \par 
l.14 
     
? 
```

Can you look into this?

BR, Akira

**Comment by schlcht** [comment]
Many thanks for the report. Could you try with: 

```
\makeatletter
\long\def\MT@prot@l#1{%
  \MT@get@prot{#1}{left}%
  \leavevmode
  #1}
\def\MT@prot@group@@{%
    \catcode`\\=0
    \catcode`\^^M=10
    \makeatletter
    {\expandafter\MT@prot@l\expandafter
      {\expandafter\scantokens\expandafter{\the\MT@toks\noexpand}}}%
  \endgroup}
\makeatother
```

(BTW: Are you sure that `hyperref` and the footnote are involved? I get the error only at `\maketitle`)

**Comment by akiyks** [comment]
Ah, I thought it was minimal, but apparently wasn't.
hyperref and footnote don't involved here.

Your fix to v3.0a works fine.
Thank you for the quick fix.  Much appreciated!

**Comment by davidcarlisle** [comment]
I haven't traced this fully but `\scantokens` here seems a bit dangerous, adding `\makeatletter` makes package code safe again but may break code that originally came from the document with @ catcode12, it will also I fail if any expl3 code has been picked up as the expl3 catcode regime will be lost in the rescan. you can't add \ExplSyntaxOn to match \makeatletter as that will prevent _ as subscript  and lose all spaces.

**Comment by schlcht** [comment]
@davidcarlisle Thanks for your comment, I think I found a way to avoid the rescanning while still allowing verbatim material etc.:

```
\def\MT@prot@group#{\bgroup\afterassignment\MT@prot@get@firstchar\let\MT@temp= }
```

**Comment by akiyks** [comment]
FWIW, current dev branch (d9a231543c19ac18c1a2a7ffb9b6287a241d5edd) works with my (not the minimal) document.
