### ISSUE TITLE
Using this package seems to suppress overful hbox warnings

### ISSUE THREAD

**Issue by claell** [schlcht/microtype#32]
## Description
As written, I have discovered, that overful hbox warnings are no longer displayed for me after using this package. The problems of the overful boxes aren't fixed, though. Thus, I expected to still get warnings for them.

_Please also indicate the engine(s) with which the issue occurs: pdfTeX_

## Minimal example demonstrating the issue
I'll try to give one if requested. Right now, I mostly wanted to document this (but I am happy to help with tracking this down).

**Comment by schlcht** [comment]
microtype can _fix_ many overfull hbox issues by applying font expansion, but it will never _suppress_ any warnings for unfixed problems. So please provide a minimal example.

**Comment by claell** [comment]
Alright. I'll try to send one next week!

**Comment by schlcht** [comment]
any news? otherwise I'm tempted to close this...

**Comment by schlcht** [comment]
feel free to re-open with a minimal example

**Comment by claell** [comment]
Note to myself: Found the most likely affected document (Exposé). However, couldn't reproduce it with the commits from the past (TeX Live 2024).
