### ISSUE TITLE
Failure to apply tracking to certain strings when using junicode

### ISSUE THREAD

**Issue by fr-peter** [schlcht/microtype#39]
## Description
I am using junicodevf in the latest TeX Live distribution. When using small capitals, I have found that words containing the string "ectio" do not have the desired tracking applied. This only happens when the option `Renderer=Harfbuzz` is present in the fontspec command that sets the font (which is done by the junicodevf package). When the font is loaded without this option, all words receive the desired tracking.

The engine used is lualatex.

[I brought the issue to the junicode github.](https://github.com/psb1558/Junicode-font/issues/292) It was suggested that it should be reported to microtype and luaotfload.

## Minimal example demonstrating the issue
```
% !TEX TS-program = lualatex
\documentclass{article}
\usepackage{junicodevf}
% behaviour also happens when using the non-variable version. does not happen if either junicode package is not used.
\usepackage[tracking=true]{microtype}


\begin{document}
\scshape I found that the word “section” does not have proper tracking. After some testing, it's not just section, but any word with the string “ectio” in it will fail to have proper tracking.

electioneering deflection: in these examples, “lection” does not have proper tracking, but the other characters do.

Interestingly, putting a hyphen, en-dash, or em-dash immediately before or after the affected word will cause it to appear properly: section-electioneering---selection

\end{document}
```
## Output
![image](https://github.com/user-attachments/assets/ccb391e7-64c3-43aa-b0a2-33cad942788a)

**Comment by fr-peter** [comment]
[I’ve been told this is a luaotfload bug,](https://github.com/latex3/luaotfload/issues/286#issuecomment-2271663628) so I’m closing this issue.

**Comment by schlcht** [comment]
Fascinating... Looking forward to learning what causes this issue.
