### ISSUE TITLE
Microtype incompatibility with \maketitle

### ISSUE THREAD

**Issue by MisterFiLou** [schlcht/microtype#5]
Following code gives an error. Don't know why.
option nopatch=item avoids the problem.

```
\documentclass[a4paper]{report}

\usepackage{microtype} 

\author{Bug}
\title{Microtype and maketitle}

\begin{document}
\maketitle
test and test
\end{document}
```

**Comment by sergiokapone** [comment]
https://tex.stackexchange.com/questions/625610/microtype-package-with-documentclass-book-in-maketitle-bug

**Comment by schlcht** [comment]
This is the same as #3. Please try with the (combined) fix: 

```
\makeatletter
\long\def\MT@prot@l#1{%
  \MT@get@prot{#1}{left}%
  \leavevmode
  #1}
\def\MT@prot@group#{\bgroup\afterassignment\MT@prot@get@firstchar\let\MT@temp= }
\makeatother
```

**Comment by sergiokapone** [comment]
Yes, thank you. I will rollback to 3.0 for now and  wait for the new version. Anyway, thanks for your work.

**Comment by schlcht** [comment]
update is on its way to CTAN
