### ISSUE TITLE
Advanced microtype automatic?

### ISSUE THREAD

**Issue by hpvd** [schlcht/microtype#9]
The new awesome lua-widow-control packages "detects and removes" widows in latex documents for the first time **fully automatically**.
https://ctan.org/pkg/lua-widow-control

For the removing, the needed little more text height is generated by stretching the interword spaces.
This works great so far, but in short lines it can still be noticeable.

In general, the stunning microtype package with standard settings already helps a lot for visual quality.

There are some great advanced examinations regarding "what could be done to enhance visual quality further" but keeping everything fully automatic. There is no (final working) solution/further optimization found yet:
https://github.com/gucci-on-fleek/lua-widow-control/issues/4

Question:
**=>** Do you/anybody have/has any idea/advice
how one could enhance visual quality further by benefitting even more from the microtype package in this usecase, but still keeping widow removing (generating a little more text height) and microtyping a **fully automatic** process?

Current state of function and resulting visual quality (fully automatic, v1.1.4 2022-02-04)
from package doc: http://mirrors.ctan.org/macros/luatex/generic/lua-widow-control/lua-widow-control.pdf

![2022-02-07_11h39_17](https://user-images.githubusercontent.com/5681880/152772735-2e7b3b82-9ac1-4523-ab38-b0d4327d505e.png)

**Comment by schlcht** [comment]
Thanks for bringing this package to my attention. However, I don't think there's much that microtype can do here (the two packages are operating on different levels (TeX vs. lua)), so I would suggest we continue any discussion over at https://github.com/gucci-on-fleek/lua-widow-control/issues/4.

**Comment by hpvd** [comment]
@schlcht many thanks for your valuable input to the discussion!

btw: if you are interested in other great stuff which may be a "dream team" with your stunning microtype package,
there is another new package [recommended](https://github.com/gucci-on-fleek/lua-widow-control/discussions/6#discussioncomment-2129193) also by @gucci-on-fleek which may catch your attention:

**linebreaker**, it solves some/many of the overfull hboxes in fully automated manner
https://github.com/michal-h21/linebreaking

it's not on ctan yet, but probably [on the way](https://github.com/michal-h21/linebreaking/issues/2#issuecomment-1032803716)...
